### ISSUE TITLE
Unhandled Codegen `error` on create of `.gql|graphql` file in dev.

### ISSUE THREAD

**Issue by cpreston321** [Diizzayy/nuxt-graphql-client#271]
### Environment

any

### Describe the bug

```
[unhandledRejection] Invalid Codegen Configuration!                                                                                           19:01:53

        Please make sure that your codegen config file contains the "generates" field, with a specification for the plugins you need.

        It should looks like that:

        schema:
          - my-schema.graphql
        generates:
          my-file.ts:
            - plugin1
            - plugin2
            - plugin3

  
  Please make sure that your codegen config file contains the "generates" field, with a specification for the plugins you need.
  
  It should looks like that:
  
  schema:
  - my-schema.graphql
  generates:
  my-file.ts:
  - plugin1
  - plugin2
  - plugin3
  at normalize 
  ```

### Expected behaviour

Shouldn't have any errors 

### Additional context

When creating a gql file in dev environment I receive this error.
