### ISSUE TITLE
Host on production not working

### ISSUE THREAD

**Issue by BorisKamp** [Diizzayy/nuxt-graphql-client#555]
### Environment

Production

### Describe the bug

When I set my clients like this:
```json
      'graphql-client': {
        clients: {
          default: {
            host: '',
            token: process.env.GQL_TOKEN,
            headers: {
              'Content-Type': 'application/json',
            },
          },
          system: {
            host: '',
            token: process.env.GQL_TOKEN,
            headers: {
              'Content-Type': 'application/json',
            },
          },
        },
      },
```

And have the following env vars in my `.env` file:
```
GQL_HOST=http://localhost:8055/graphql
GQL_SYSTEM_HOST=http://localhost:8055/graphql/system
```

It works great on localhost.

However, when I deploy to production, the GQL client is not defined as the .env vars are not read somehow.

If I do this:
```
      'graphql-client': {
        clients: {
          default: {
            host: process.env.GQL_HOST ?? 'https://directus-mijn.controlenergy.nl/graphql',
            token: process.env.GQL_TOKEN,
            headers: {
              'Content-Type': 'application/json',
            },
          },
          system: {
            host: process.env.GQL_SYSTEM_HOST ?? 'https://directus-mijn.controlenergy.nl/graphql/system',
            token: process.env.GQL_TOKEN,
            headers: {
              'Content-Type': 'application/json',
            },
          },
        },
      },
```

It does work on production as there is a default value. But this default value is not overwritten by my server's env var.
The `docker-compose.yml` I use has these env's:
```yml
services:
  cebv-portal-nuxt:
    container_name: ...
    image: ...
    environment:
      - NUXT_PUBLIC_SITE_URL=https://mijn.controlenergy.nl
      - GQL_HOST=https://test.directus-mijn.controlenergy.nl/graphqllllll
      - GQL_SYSTEM_HOST=https://test.directus-mijn.controlenergy.nl/graphql/system
      - .....
```

But it still uses `https://directus-mijn.controlenergy.nl/graphql/system` instead of `https://test.directus-mijn.controlenergy.nl/graphql/system` for example....

@Diizzayy why is this?

### Expected behaviour

See above
